name: abc
on:
  push
permissions:
  packages: write
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: step1
      run: |
        docker --version
        docker images
        ls -larth
        docker build -t ghcr.io/asif741852014/myfirstimage:v1.0.0 .
        docker images
        docker run --name myfirstimage123 ghcr.io/asif741852014/myfirstimage:v1.0.0

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: asif741852014
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: docker push ghcr.io/asif741852014/myfirstimage:v1.0.0