name: abc
on:
  push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: step1
      run: |
        docker --version
        docker images
        ls -larth
        docker build -t myfirstimage:v1.0.0 .
        docker images

